version: '3.8'

services:
  mysql:
    container_name: 'path_mysql'
    build:
      context: './docker/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-secret}'
      MYSQL_USER: '${MYSQL_USER:-path}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-path}'
    ports:
      - '8878:3306'
    volumes:
      - './docker/data/mysql:/var/lib/mysql'
  phpmyadmin:
    container_name: 'path_phpmyadmin'
    build:
      context: './docker/phpmyadmin'
    restart: 'unless-stopped'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: '${PHPMYADMIN_UPLOAD_LIMIT:-2000M}'
    depends_on:
      - mysql
    ports:
      - '8879:80'
  php:
    container_name: 'path_php'
    build:
      context: './docker/php-fpm'
    volumes:
      - './:/var/www/site'
    depends_on:
      - mysql
  nginx:
    container_name: 'path_nginx'
    build:
      context: './docker/nginx'
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/site'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
